# Generated by Django 4.1 on 2023-01-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_id", models.IntegerField()),
                ("city", models.CharField(max_length=30)),
                ("state_id", models.IntegerField()),
                ("is_default", models.IntegerField(blank=True, null=True)),
                ("is_active", models.IntegerField()),
                ("sort_order", models.IntegerField()),
                ("lang", models.CharField(max_length=10)),
                ("created_at", models.CharField(max_length=10)),
                ("updated_at", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={"db_table": "cities", "managed": False,},
        ),
        migrations.CreateModel(
            name="Countries",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=20)),
                ("country_code", models.CharField(max_length=2, unique=True)),
                ("dial_code", models.CharField(max_length=5)),
                ("currency_name", models.CharField(max_length=20)),
                (
                    "currency_symbol",
                    models.CharField(db_collation="utf8_unicode_ci", max_length=20),
                ),
                ("currency_code", models.CharField(max_length=10)),
                ("country_status", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "countries", "managed": False,},
        ),
        migrations.CreateModel(
            name="States",
            fields=[
                ("state_id", models.IntegerField(primary_key=True, serialize=False)),
                ("state", models.CharField(blank=True, max_length=40, null=True)),
                ("country_id", models.IntegerField(blank=True, null=True)),
                ("is_active", models.IntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("lang", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={"db_table": "states", "managed": False,},
        ),
    ]
