# Generated by Django 4.1 on 2023-01-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_resume_bachelor_gpa_alter_resume_doctor_gpa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="attachment",
            field=models.FileField(
                blank=True, upload_to="file/", verbose_name="Attachment"
            ),
        ),
    ]
