# Generated by Django 4.1 on 2022-12-18 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="cretaed_date",),
        migrations.AddField(
            model_name="job",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_city",
            field=models.SmallIntegerField(
                choices=[
                    (0, "New York"),
                    (1, "Chicago"),
                    (2, "Boston"),
                    (3, "Los Angeles"),
                ],
                verbose_name="Job City",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Technology"),
                    (1, "Product"),
                    (2, "Management"),
                    (3, "Design"),
                ],
                verbose_name="Job Type",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="modified_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Modified Date"
            ),
        ),
    ]
