# Generated by Django 4.1 on 2023-01-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_resume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resume",
            options={"verbose_name": "Resume", "verbose_name_plural": "Resume List"},
        ),
    ]
