# Generated by Django 4.1 on 2023-01-02 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userid",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="Candidate ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=135, verbose_name="Candidate Name"),
                ),
                ("city", models.CharField(max_length=135, verbose_name="City")),
                ("phone", models.CharField(max_length=135, verbose_name="Phone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=135, verbose_name="Email"),
                ),
                (
                    "apply_position",
                    models.CharField(
                        blank=True, max_length=135, verbose_name="Applied Position"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=135, verbose_name="Address"
                    ),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=135, verbose_name="Gender"),
                ),
                (
                    "candidate_remark",
                    models.CharField(blank=True, max_length=135, verbose_name="Remark"),
                ),
                (
                    "bachelor_school",
                    models.CharField(
                        blank=True,
                        max_length=135,
                        verbose_name="Undergraduate School or College",
                    ),
                ),
                (
                    "master_school",
                    models.CharField(
                        blank=True,
                        max_length=135,
                        verbose_name="Graduate School or College",
                    ),
                ),
                (
                    "doctor_school",
                    models.CharField(
                        blank=True, max_length=135, verbose_name="PHD School or College"
                    ),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=135, verbose_name="Major"),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Undergraduate", "Undergraduate"),
                            ("Graduate", "Graduate"),
                            ("Phd", "Phd"),
                        ],
                        max_length=135,
                        verbose_name="Education Level",
                    ),
                ),
                (
                    "test_score_of_general_ability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="General Test Score",
                    ),
                ),
                (
                    "test_score_of_professional_ability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Professional Test Score",
                    ),
                ),
                (
                    "first_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Between1-5，Extraordinary: >=4.5，Excellent: 4-4.4，Good: 3.5-3.9，General: 3-3.4，Bad: <3",
                        max_digits=2,
                        null=True,
                        verbose_name="First Round Score",
                    ),
                ),
                (
                    "first_learning_ability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="Learning Ability Score",
                    ),
                ),
                (
                    "first_professional_competency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="Professional Ability Score",
                    ),
                ),
                (
                    "first_advantage",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="Advantage"
                    ),
                ),
                (
                    "first_disadvantage",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="Disadvantage"
                    ),
                ),
                (
                    "first_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Recommended to next round", "Recommended to next round"),
                            ("Waiting list", "Waiting list"),
                            ("Failed", "Failed"),
                        ],
                        max_length=256,
                        verbose_name="First Round Result",
                    ),
                ),
                (
                    "first_recommend_position",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Recommended Position"
                    ),
                ),
                (
                    "first_remark",
                    models.CharField(
                        blank=True, max_length=135, verbose_name="First Round Remark"
                    ),
                ),
                (
                    "second_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Between1-5，Extraordinary: >=4.5，Excellent: 4-4.4，Good: 3.5-3.9，General: 3-3.4，Bad: <3",
                        max_digits=2,
                        null=True,
                        verbose_name="Second Round Score",
                    ),
                ),
                (
                    "second_learning_ability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="Learning Ability Score",
                    ),
                ),
                (
                    "second_professional_competency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="Professional Ability Score",
                    ),
                ),
                (
                    "second_pursue_of_excellence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="Excellence Pursue Score",
                    ),
                ),
                (
                    "second_communication_ability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="Communication Ability Score",
                    ),
                ),
                (
                    "second_pressure_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="Under Pressure Score",
                    ),
                ),
                (
                    "second_advantage",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="Advantage"
                    ),
                ),
                (
                    "second_disadvantage",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="Disadvantage"
                    ),
                ),
                (
                    "second_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Recommended to be hired", "Recommended to be hired"),
                            ("Waiting list", "Waiting list"),
                            ("Failed", "Failed"),
                        ],
                        max_length=256,
                        verbose_name="Second Round Result",
                    ),
                ),
                (
                    "second_recommend_position",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Recommended Position"
                    ),
                ),
                (
                    "second_remark",
                    models.CharField(
                        blank=True, max_length=135, verbose_name="Second Round Remark"
                    ),
                ),
                (
                    "hr_score",
                    models.CharField(
                        blank=True,
                        choices=[("S", "S"), ("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=10,
                        verbose_name="HR Score",
                    ),
                ),
                (
                    "hr_responsibility",
                    models.CharField(
                        blank=True,
                        choices=[("S", "S"), ("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=10,
                        verbose_name="HR Responsibility",
                    ),
                ),
                (
                    "hr_communication_ability",
                    models.CharField(
                        blank=True,
                        choices=[("S", "S"), ("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=10,
                        verbose_name="HR Communication Ability",
                    ),
                ),
                (
                    "hr_logic_ability",
                    models.CharField(
                        blank=True,
                        choices=[("S", "S"), ("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=10,
                        verbose_name="HR Logic Ability",
                    ),
                ),
                (
                    "hr_potential",
                    models.CharField(
                        blank=True,
                        choices=[("S", "S"), ("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=10,
                        verbose_name="HR Potential",
                    ),
                ),
                (
                    "hr_stability",
                    models.CharField(
                        blank=True,
                        choices=[("S", "S"), ("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=10,
                        verbose_name="HR Stability",
                    ),
                ),
                (
                    "hr_advantage",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="HR Advantage"
                    ),
                ),
                (
                    "hr_disadvantage",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="HR Disadvantage"
                    ),
                ),
                (
                    "hr_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Recommended to be hired", "Recommended to be hired"),
                            ("Waiting list", "Waiting list"),
                            ("Failed", "Failed"),
                        ],
                        max_length=256,
                        verbose_name="HR Result",
                    ),
                ),
                (
                    "hr_remark",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="HR Remark"
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Creator"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "last_editor",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Last Editor"
                    ),
                ),
                (
                    "first_interviewer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_interviewer_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="First Round Interviewer",
                    ),
                ),
                (
                    "hr_interviewer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_interviewer_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="HR Result",
                    ),
                ),
                (
                    "second_interviewer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_interviewer_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Second Round Interviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidate",
                "verbose_name_plural": "candidates",
                "db_table": "candidate",
            },
        ),
    ]
