# Generated by Django 4.1 on 2023-01-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={
                "permissions": [
                    ("export", "Can export candidate list"),
                    ("notify", "notify interviewer for candidate review"),
                ],
                "verbose_name": "candidate",
                "verbose_name_plural": "candidates",
            },
        ),
    ]
