# Generated by Django 4.1 on 2023-01-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0003_candidate_bachelor_gpa_candidate_doctor_gpa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="bachelor_GPA",
            field=models.CharField(
                blank=True, max_length=135, null=True, verbose_name="Undergraduate GPA"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="doctor_GPA",
            field=models.CharField(
                blank=True, max_length=135, null=True, verbose_name="Phd GPA"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="master_GPA",
            field=models.CharField(
                blank=True, max_length=135, null=True, verbose_name="Graduate GPA"
            ),
        ),
    ]
