export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_RESUME_REQUEST = 'USER_RESUME_REQUEST'
export const USER_RESUME_SUCCESS = 'USER_RESUME_SUCCESS'
export const USER_RESUME_FAIL = 'USER_RESUME_FAIL'

export const USER_RESUME_UPDATE_REQUEST = 'USER_RESUME_UPDATE_REQUEST'
export const USER_RESUME_UPDATE_SUCCESS = 'USER_RESUME_UPDATE_SUCCESS'
export const USER_RESUME_UPDATE_FAIL = 'USER_RESUME_UPDATE_FAIL'